apiVersion: apps/v1
kind: Deployment
metadata:
  name: arvindveerelli/similarity-search-application-ui

spec:
  replicas: 1
  selector:
    matchLabels:
      app: arvindveerelli/similarity-search-application-ui
  template:
    metadata:
      labels:
        app: arvindveerelli/similarity-search-application-ui
    spec:
      containers:
      - name: arvindveerelli/similarity-search-application-ui
        image: arvindveerelli/similarity-search-application-ui:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
        - containerPort: 8501
        resources:
          limits:
            memory: "5Gi"
            cpu: "6"
          requests:
            memory: "5Gi"
            cpu: "6"
