apiVersion: v1
kind: Service
metadata:
  name: arvindveerelli/similarity-search-application-ui
spec:
  selector:
    app: arvindveerelli/similarity-search-application-ui
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      nodePort: 32000
    - protocol: TCP
      port: 8501
      targetPort: 8501
      nodePort: 32001
  type: NodePort
